server:
  port: 10100

logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

zuul:
  routes:
    crawler:
      path: /crawler/**
      url: http://localhost:10200
      stripPrefix: false
    bookmarks:
      path: /bookmarks/**
      url: http://localhost:10300
      stripPrefix: false

---

spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
