logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints: 
  shutdown: 
    enabled: true

server:
    port: ${PORT:0}
